version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - drupal_core:/app/web:ro
    links:
      - php
  
  # PHP
  php:
    # custom build based on d8-fpm
    build: docker/newcity-d8/.
    image: newcity-d8
    volumes:
      # Drupal is in the web directory, but core is maintained in Docker persistent storage
      # this means composer should be run on the container
      - drupal_core:/app/web
      - ./themes/custom:/app/web/themes/custom
      - ./modules/custom:/app/web/modules/custom
      - ./modules/contrib:/app/web/modules/contrib
      - ./libraries:/app/web/libraries
      - ./utils:/app/utils
      - ./composer.json:/app/composer.json
    links:
      - database
    working_dir: /app
    restart: always

  # MySQL Server
  database:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
  drupal_core:
  
